// yeying/src/components/Footer.vue
<script lang="ts" setup>
import logoUrl from '@/assets/img/logo.svg'
import { useTranslate } from '@/lang/messages'

const t = useTranslate()
</script>

<template>
  <footer class="mt-20 border-t border-gray-200 bg-white/80">
    <div class="mx-auto max-w-6xl px-5 py-10 lg:px-0">
      <div class="flex flex-col justify-between gap-8 sm:flex-row sm:items-center">
        <img class="h-8 w-auto" :src="logoUrl" alt="YeYing" />
        <div class="flex flex-wrap items-center gap-x-6 gap-y-3 text-sm text-gray-700">
          <RouterLink class="focus-ring rounded-lg hover:text-yeying-blue" to="/docs">{{ t('h_docs') }}</RouterLink>
          <a class="focus-ring rounded-lg hover:text-yeying-blue" href="https://github.com/yeying-community" target="_blank" rel="noreferrer">GitHub</a>
          <a class="focus-ring rounded-lg hover:text-yeying-blue" :href="`mailto:${t('footer_email')}`">{{ t('footer_email') }}</a>
        </div>
      </div>
      <div class="mt-8 flex flex-col justify-between gap-3 border-t border-gray-200 pt-6 text-xs text-gray-500 sm:flex-row">
        <div class="flex flex-wrap gap-x-4 gap-y-2">
          <a href="https://beian.mps.gov.cn/#/query/webSearch?code=33010902004112" target="_blank" rel="noreferrer">{{ t('footer_public_security_record') }}</a>
          <a href="https://beian.miit.gov.cn/" target="_blank" rel="noreferrer">{{ t('footer_icp_record') }}</a>
        </div>
        <span>{{ t('footer_copyright') }}</span>
      </div>
    </div>
  </footer>
</template>

// tidukongjian/components/Footer.tsx
export default function Footer() {
  return (
    <footer className="py-12 mt-auto">
      <div className="mx-auto max-w-6xl px-4 flex flex-col gap-8 md:flex-row md:items-start md:justify-between">
        <div className="text-left">
          <p className="text-gray-600 mb-6">@2026 梯度空间(杭州)科技有限公司</p>
          <div className="text-gray-500 space-y-2">
            <a
              href="https://beian.miit.gov.cn/#/Integrated/index"
              target="_blank"
              rel="noreferrer"
              className="block hover:text-blue-600 transition-colors"
            >
              浙ICP备2025164887号-2
            </a>
            <a
              href="https://beian.mps.gov.cn/#/query/webSearch?code=33019202002822"
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1 hover:text-blue-600 transition-colors"
            >
              <img
                src="/images/police-icon.png"
                alt=""
                className="h-[1em] w-auto"
              />
              浙公网安备33019202002822号
            </a>
          </div>
        </div>

        <div className="space-y-2 text-left text-gray-600">
          <p>联系电话：17706514288</p>
          <p>邮箱：tidukongjian@163.com</p>
          <p>微信公众号：梯度空间</p>
          <p>小红书：梯度空间</p>
        </div>
      </div>
    </footer>
  );
}
